title: HowTos
desription: Topics across Computer Science
repository: jfspps/howtos # for github-metadata
baseurl: "/howtos" # the subpath of your site, e.g. /blog
url: "https://jfspps.github.io" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: just-the-docs/just-the-docs
favicon_ico: "/images/favicon.ico"
color_scheme: dark

# remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

permalink: pretty

enable_copy_code_button: true
search.button: true # bottom-right search button

gh_edit_repository: "https://github.com/jfspps/howtos" # the github URL for your repo