title: "HowTos"
remote_theme: just-the-docs/just-the-docs
favicon_ico: "/images/favicon.ico"
# Aux links for the upper right navigation
aux_links:
  "HowTos":
    - "https://jfspps.github.io/howtos/"
color_scheme: dark

# remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one